version: 2

models:
  - name: fact_sales
    columns:
      - name: OrderDateKey
        tests:
          - not_null
      - name: ProductKey
        tests:
          - not_null
      - name: CustomerKey
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: CustomerKey

  - name: dim_customer
    columns:
      - name: CustomerKey
        tests:
          - not_null
          - unique